apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mailhog
  template:
    metadata:
      labels:
        component: mailhog
    spec:
      containers:
        - name: mailhog
          image: 'mailhog/mailhog:latest'
          ports:
            - containerPort: 8025
            - containerPort: 1025
          imagePullPolicy: Always
