apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
spec:
  type: ClusterIP
  selector:
    component: mailhog
  ports:
    - name: port8025
      port: 8025
      targetPort: 8025
    - name: port1025
      port: 1025
      targetPort: 1025