apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  type: ClusterIP
  selector:
    component: ui
  ports:
    - port: 80
      targetPort: 80

# apiVersion: v1
# kind: Service
# metadata:
#   name: ui-service
# spec:
#   selector:
#     app: api-service
#     tier: frontend
#   ports:
#   - protocol: "TCP"
#     port: 80
#     targetPort: 80