# apiVersion: v1
# kind: Service
# metadata:
#   name: api-service
# spec:
#   type: ClusterIP
#   selector:
#     component: api
#   ports:
#     - port: 8080
#       targetPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    component: api
  ports:
    - port: 8080
      nodePort: 32500
      # targetPort: 8080

# apiVersion: v1
# kind: Service
# metadata:
#   name: api-service
# spec:
#   selector:
#     app: api-service
#     tier: backend
#   ports:
#   - protocol: "TCP"
#     port: 8080
#     targetPort: http